# pubspec.yaml
name: shade_transfer
description: Peer-to-peer encrypted file transfer.
version: 0.0.1
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter

  shadcn_ui:
  flutter_webrtc:
  nfc_manager:
  file_picker:
  pointycastle:
  crypto:
  shared_preferences:
  flutter_secure_storage:
  qr_flutter:
  path_provider:
  permission_handler:
  convert:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:

flutter:
  uses-material-design: true